version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: imas-sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - imas-network

  # Main API Gateway Service
  api-gateway:
    build:
      context: .
      dockerfile: imas-BE/imas.ApiService/Dockerfile
    container_name: imas-api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ImasMainDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
      - ModuleCommunication__Mode=Distributed
      - ModuleCommunication__ServiceEndpoints__HR=http://hr-service:80
      - ModuleCommunication__ServiceEndpoints__Assets=http://assets-service:80
      - ModuleCommunication__ServiceEndpoints__Finance=http://finance-service:80
      - ModuleCommunication__ServiceEndpoints__General=http://general-service:80
    ports:
      - "7000:443"
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - imas-network

  # HR Microservice
  hr-service:
    build:
      context: .
      dockerfile: imas-BE/imas.HR.ApiService/Dockerfile
    container_name: imas-hr-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ImasHRDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
      - ModuleCommunication__Mode=Distributed
    ports:
      - "7005:443"
      - "5005:80"
    depends_on:
      - sqlserver
    networks:
      - imas-network

  # Assets Microservice
  assets-service:
    build:
      context: .
      dockerfile: imas-BE/imas.Assets.ApiService/Dockerfile
    container_name: imas-assets-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ImasAssetsDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
      - ModuleCommunication__Mode=Distributed
    ports:
      - "7006:443"
      - "5006:80"
    depends_on:
      - sqlserver
    networks:
      - imas-network

  # Finance Microservice
  finance-service:
    build:
      context: .
      dockerfile: imas-BE/imas.Finance.ApiService/Dockerfile
    container_name: imas-finance-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ImasFinanceDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
      - ModuleCommunication__Mode=Distributed
    ports:
      - "7007:443"
      - "5007:80"
    depends_on:
      - sqlserver
    networks:
      - imas-network

  # General Microservice
  general-service:
    build:
      context: .
      dockerfile: imas-BE/imas.General.ApiService/Dockerfile
    container_name: imas-general-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ImasGeneralDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
      - ModuleCommunication__Mode=Distributed
    ports:
      - "7008:443"
      - "5008:80"
    depends_on:
      - sqlserver
    networks:
      - imas-network

  # Web Frontend
  web-frontend:
    build:
      context: .
      dockerfile: imas-FE/imas.Web/Dockerfile
    container_name: imas-web-frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - WeatherApiUrl=http://api-gateway:80
    ports:
      - "7100:443"
      - "5100:80"
    depends_on:
      - api-gateway
    networks:
      - imas-network

volumes:
  sqlserver_data:

networks:
  imas-network:
    driver: bridge