// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mara.ApiService.Infrastructure.Data;

#nullable disable

namespace mara.ApiService.Migrations
{
    [DbContext(typeof(MaraDbContext))]
    [Migration("20250913170328_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mara.ApiService.Modules.Authentication.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 13, 17, 3, 27, 781, DateTimeKind.Utc).AddTicks(6982),
                            Email = "admin@mara.com",
                            PasswordHash = "$2a$11$sf3pQ60j5DQv2MFRJJkgJuyC2IlkZk5uhRMNvEWOUZoxsfjI5jafS",
                            Roles = "[]",
                            UpdatedAt = new DateTime(2025, 9, 13, 17, 3, 27, 781, DateTimeKind.Utc).AddTicks(6989),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("mara.ApiService.Modules.Todos.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("mara.ApiService.Modules.Weather.WeatherForecast", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = "seed_new york_0",
                            Date = new DateOnly(2025, 9, 14),
                            Location = "New York",
                            Summary = "Balmy",
                            TemperatureC = -6
                        },
                        new
                        {
                            Id = "seed_london_0",
                            Date = new DateOnly(2025, 9, 14),
                            Location = "London",
                            Summary = "Mild",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = "seed_tokyo_0",
                            Date = new DateOnly(2025, 9, 14),
                            Location = "Tokyo",
                            Summary = "Freezing",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = "seed_sydney_0",
                            Date = new DateOnly(2025, 9, 14),
                            Location = "Sydney",
                            Summary = "Mild",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = "seed_berlin_0",
                            Date = new DateOnly(2025, 9, 14),
                            Location = "Berlin",
                            Summary = "Cool",
                            TemperatureC = 1
                        },
                        new
                        {
                            Id = "seed_new york_1",
                            Date = new DateOnly(2025, 9, 15),
                            Location = "New York",
                            Summary = "Freezing",
                            TemperatureC = 2
                        },
                        new
                        {
                            Id = "seed_london_1",
                            Date = new DateOnly(2025, 9, 15),
                            Location = "London",
                            Summary = "Freezing",
                            TemperatureC = 24
                        },
                        new
                        {
                            Id = "seed_tokyo_1",
                            Date = new DateOnly(2025, 9, 15),
                            Location = "Tokyo",
                            Summary = "Warm",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = "seed_sydney_1",
                            Date = new DateOnly(2025, 9, 15),
                            Location = "Sydney",
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = "seed_berlin_1",
                            Date = new DateOnly(2025, 9, 15),
                            Location = "Berlin",
                            Summary = "Sweltering",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = "seed_new york_2",
                            Date = new DateOnly(2025, 9, 16),
                            Location = "New York",
                            Summary = "Bracing",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = "seed_london_2",
                            Date = new DateOnly(2025, 9, 16),
                            Location = "London",
                            Summary = "Mild",
                            TemperatureC = 32
                        },
                        new
                        {
                            Id = "seed_tokyo_2",
                            Date = new DateOnly(2025, 9, 16),
                            Location = "Tokyo",
                            Summary = "Warm",
                            TemperatureC = 26
                        },
                        new
                        {
                            Id = "seed_sydney_2",
                            Date = new DateOnly(2025, 9, 16),
                            Location = "Sydney",
                            Summary = "Mild",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = "seed_berlin_2",
                            Date = new DateOnly(2025, 9, 16),
                            Location = "Berlin",
                            Summary = "Warm",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = "seed_new york_3",
                            Date = new DateOnly(2025, 9, 17),
                            Location = "New York",
                            Summary = "Bracing",
                            TemperatureC = 1
                        },
                        new
                        {
                            Id = "seed_london_3",
                            Date = new DateOnly(2025, 9, 17),
                            Location = "London",
                            Summary = "Scorching",
                            TemperatureC = -4
                        },
                        new
                        {
                            Id = "seed_tokyo_3",
                            Date = new DateOnly(2025, 9, 17),
                            Location = "Tokyo",
                            Summary = "Bracing",
                            TemperatureC = -1
                        },
                        new
                        {
                            Id = "seed_sydney_3",
                            Date = new DateOnly(2025, 9, 17),
                            Location = "Sydney",
                            Summary = "Cool",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = "seed_berlin_3",
                            Date = new DateOnly(2025, 9, 17),
                            Location = "Berlin",
                            Summary = "Chilly",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = "seed_new york_4",
                            Date = new DateOnly(2025, 9, 18),
                            Location = "New York",
                            Summary = "Freezing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = "seed_london_4",
                            Date = new DateOnly(2025, 9, 18),
                            Location = "London",
                            Summary = "Warm",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = "seed_tokyo_4",
                            Date = new DateOnly(2025, 9, 18),
                            Location = "Tokyo",
                            Summary = "Sweltering",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = "seed_sydney_4",
                            Date = new DateOnly(2025, 9, 18),
                            Location = "Sydney",
                            Summary = "Chilly",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = "seed_berlin_4",
                            Date = new DateOnly(2025, 9, 18),
                            Location = "Berlin",
                            Summary = "Balmy",
                            TemperatureC = 27
                        },
                        new
                        {
                            Id = "seed_new york_5",
                            Date = new DateOnly(2025, 9, 19),
                            Location = "New York",
                            Summary = "Bracing",
                            TemperatureC = -4
                        },
                        new
                        {
                            Id = "seed_london_5",
                            Date = new DateOnly(2025, 9, 19),
                            Location = "London",
                            Summary = "Hot",
                            TemperatureC = 24
                        },
                        new
                        {
                            Id = "seed_tokyo_5",
                            Date = new DateOnly(2025, 9, 19),
                            Location = "Tokyo",
                            Summary = "Warm",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = "seed_sydney_5",
                            Date = new DateOnly(2025, 9, 19),
                            Location = "Sydney",
                            Summary = "Freezing",
                            TemperatureC = 19
                        },
                        new
                        {
                            Id = "seed_berlin_5",
                            Date = new DateOnly(2025, 9, 19),
                            Location = "Berlin",
                            Summary = "Cool",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = "seed_new york_6",
                            Date = new DateOnly(2025, 9, 20),
                            Location = "New York",
                            Summary = "Warm",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = "seed_london_6",
                            Date = new DateOnly(2025, 9, 20),
                            Location = "London",
                            Summary = "Bracing",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = "seed_tokyo_6",
                            Date = new DateOnly(2025, 9, 20),
                            Location = "Tokyo",
                            Summary = "Warm",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = "seed_sydney_6",
                            Date = new DateOnly(2025, 9, 20),
                            Location = "Sydney",
                            Summary = "Chilly",
                            TemperatureC = 21
                        },
                        new
                        {
                            Id = "seed_berlin_6",
                            Date = new DateOnly(2025, 9, 20),
                            Location = "Berlin",
                            Summary = "Bracing",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = "seed_new york_7",
                            Date = new DateOnly(2025, 9, 21),
                            Location = "New York",
                            Summary = "Warm",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = "seed_london_7",
                            Date = new DateOnly(2025, 9, 21),
                            Location = "London",
                            Summary = "Freezing",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = "seed_tokyo_7",
                            Date = new DateOnly(2025, 9, 21),
                            Location = "Tokyo",
                            Summary = "Chilly",
                            TemperatureC = 19
                        },
                        new
                        {
                            Id = "seed_sydney_7",
                            Date = new DateOnly(2025, 9, 21),
                            Location = "Sydney",
                            Summary = "Sweltering",
                            TemperatureC = -6
                        },
                        new
                        {
                            Id = "seed_berlin_7",
                            Date = new DateOnly(2025, 9, 21),
                            Location = "Berlin",
                            Summary = "Warm",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = "seed_new york_8",
                            Date = new DateOnly(2025, 9, 22),
                            Location = "New York",
                            Summary = "Cool",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = "seed_london_8",
                            Date = new DateOnly(2025, 9, 22),
                            Location = "London",
                            Summary = "Freezing",
                            TemperatureC = 11
                        },
                        new
                        {
                            Id = "seed_tokyo_8",
                            Date = new DateOnly(2025, 9, 22),
                            Location = "Tokyo",
                            Summary = "Cool",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = "seed_sydney_8",
                            Date = new DateOnly(2025, 9, 22),
                            Location = "Sydney",
                            Summary = "Cool",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = "seed_berlin_8",
                            Date = new DateOnly(2025, 9, 22),
                            Location = "Berlin",
                            Summary = "Chilly",
                            TemperatureC = 23
                        },
                        new
                        {
                            Id = "seed_new york_9",
                            Date = new DateOnly(2025, 9, 23),
                            Location = "New York",
                            Summary = "Chilly",
                            TemperatureC = 12
                        },
                        new
                        {
                            Id = "seed_london_9",
                            Date = new DateOnly(2025, 9, 23),
                            Location = "London",
                            Summary = "Balmy",
                            TemperatureC = -9
                        },
                        new
                        {
                            Id = "seed_tokyo_9",
                            Date = new DateOnly(2025, 9, 23),
                            Location = "Tokyo",
                            Summary = "Hot",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = "seed_sydney_9",
                            Date = new DateOnly(2025, 9, 23),
                            Location = "Sydney",
                            Summary = "Balmy",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = "seed_berlin_9",
                            Date = new DateOnly(2025, 9, 23),
                            Location = "Berlin",
                            Summary = "Hot",
                            TemperatureC = 25
                        });
                });

            modelBuilder.Entity("mara.ApiService.Modules.Todos.Todo", b =>
                {
                    b.HasOne("mara.ApiService.Modules.Authentication.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
